### ISSUE TITLE
Swagger 2.0 Support

### ISSUE THREAD

**Issue by Graham42** [mulesoft/swagger-to-raml-object#3]
For someone who wants to try out both Swagger and RAML and started by writing a prototype spec in the Swagger editor, this would be really useful. The [Swagger editor](http://editor.swagger.io/) defaults to Swagger 2.0

**Comment by blakeembrey** [comment]
@Graham42 That's definitely on the roadmap, but I'm not sure when we'll have time to get around to it. Have you come across any third party tooling available for this?

**Comment by Graham42** [comment]
The only other conversion tool that I came across was https://github.com/8x8Cloud/swagger2raml/. 

There's an interesting GUI tool, [Restlet Studio](http://studio.restlet.com/), that outputs both Swagger 2.0 and RAML. However, it forces the use of the GUI and doesn't allow raw editing. 

I've ended up trying RAML by running [API Designer](https://github.com/mulesoft/api-designer) locally, and so far found it to be an awesome tool.

**Comment by JaniszM** [comment]
Is someone tried https://www.npmjs.com/package/api-spec-converter ?

**Comment by aquette** [comment]
Hi, any news on swagger 2.0 support?

**Comment by sichvoge** [comment]
Hi. I think you should try out https://github.com/mulesoft/oas-raml-converter. That's more probably to last.

**Comment by Graham42** [comment]
@sichvoge thanks! That looks to be what I was hoping for.

**Comment by sichvoge** [comment]
It also has some nice web ui that you can use to test. Please bear in mind its WIP and any feedback, bug hunting, or what ever would make us really happy :)
